name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: build
        uses: actions/checkout@v2
      - run: docker build -t sanjayvrs/multi-client-10-14 ./client
      - run: docker build -t sanjayvrs/multi-nginx-10-14 ./nginx
      - run: docker build -t sanjayvrs/multi-server-10-14 ./server
      - run: docker build -t sanjayvrs/multi-worker-10-14 ./worker
 
      - run: docker push sanjayvrs/multi-client-10-14
      - run: docker push sanjayvrs/multi-nginx-10-14
      - run: docker push sanjayvrs/multi-server-10-14
      - run: docker push sanjayvrs/multi-worker-10-14


      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multigh-env
          existing_bucket_name: awscicdsanjay
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

