name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  
      - run: docker build -t sanjayvrs/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true sanjayvrs/react-test npm test
      - run: docker build -t sanjayvrs/test-client ./client  
      - run: docker push sanjayvrs/test-client
  

